# Generated by Django 4.1.1 on 2022-12-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_author'),
        ('issues', '0006_autopopulate'),
    ]

    operations = [
    ]
