# Generated by Django 4.1.1 on 2022-12-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_alter_customuser_email'),
        ('accounts', '0004_populate_type'),
    ]

    operations = [
    ]
