# Generated by Django 4.1.3 on 2022-12-08 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_merge_20221205_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_token",
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
