# Generated by Django 4.1.3 on 2022-12-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_auth_token_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="type",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
