# Generated by Django 4.1.3 on 2022-11-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=512)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
    ]
