# Generated by Django 4.1.1 on 2022-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("price", models.DecimalField(decimal_places=2, max_digits=2)),
                ("description", models.CharField(max_length=512)),
            ],
        ),
    ]
