# Generated by Django 4.1.1 on 2022-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="image",
            field=models.ImageField(
                blank=True,
                default="https://as1.ftcdn.net/v2/jpg/03/53/11/00/1000_F_353110097_nbpmfn9iHlxef4EDIhXB1tdTD0lcWhG9.jpg",
                upload_to="",
            ),
        ),
    ]
