# Generated by Django 4.1.1 on 2022-11-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_items_image_alter_items_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
