# Generated by Django 4.1.1 on 2022-11-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_items_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
