# Generated by Django 4.1.1 on 2022-12-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_items_quantity_remove_items_size_delete_size'),
        ('items', '0005_populate_types'),
    ]

    operations = [
    ]
