# Generated by Django 4.1.1 on 2022-11-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_items_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
